-- Seed data: BCCA reference prices
-- Generated from lib/data/seed/precios-bcca.ts
INSERT INTO precios_referencia (codigo, descripcion, unidad, precio, categoria) VALUES
  ('DEM-001', 'Demolición de tabique de ladrillo hueco sencillo', 'm²', 5.80, 'Demolición'),
  ('DEM-002', 'Demolición de tabique de ladrillo hueco doble', 'm²', 7.50, 'Demolición'),
  ('DEM-003', 'Demolición de solado cerámico con retirada', 'm²', 8.20, 'Demolición'),
  ('DEM-004', 'Demolición de alicatado cerámico con retirada', 'm²', 7.80, 'Demolición'),
  ('DEM-005', 'Demolición de falso techo de escayola', 'm²', 5.50, 'Demolición'),
  ('DEM-006', 'Desmontaje de sanitarios (inodoro, lavabo o bidé)', 'ud', 18.00, 'Demolición'),
  ('DEM-007', 'Desmontaje de bañera o plato de ducha', 'ud', 32.00, 'Demolición'),
  ('DEM-008', 'Desmontaje de puerta interior con marco', 'ud', 12.50, 'Demolición'),
  ('DEM-009', 'Desmontaje de ventana con marco', 'ud', 15.00, 'Demolición'),
  ('DEM-010', 'Retirada de instalación eléctrica existente', 'ml', 3.20, 'Demolición'),
  ('DEM-011', 'Retirada de escombros con contenedor', 'm³', 35.00, 'Demolición'),
  ('DEM-012', 'Picado de enfoscado en paramentos', 'm²', 6.50, 'Demolición'),
  ('DEM-013', 'Desmontaje de cocina completa (muebles y electrodomésticos)', 'ud', 280.00, 'Demolición'),
  ('DEM-014', 'Apertura de hueco en muro de carga (incluye apeo)', 'ud', 850.00, 'Demolición'),
  ('ALB-001', 'Enfoscado maestreado en paramentos verticales', 'm²', 18.50, 'Albañilería'),
  ('ALB-002', 'Guarnecido y enlucido de yeso en paramentos', 'm²', 14.20, 'Albañilería'),
  ('ALB-003', 'Tabique de ladrillo hueco doble', 'm²', 22.50, 'Albañilería'),
  ('ALB-004', 'Tabique de ladrillo hueco sencillo', 'm²', 18.00, 'Albañilería'),
  ('ALB-005', 'Tabiquería de pladur con perfilería (15+46+15)', 'm²', 28.00, 'Albañilería'),
  ('ALB-006', 'Trasdosado de pladur directo a muro', 'm²', 22.00, 'Albañilería'),
  ('ALB-007', 'Recibido de cercos de puertas con mortero', 'ud', 25.00, 'Albañilería'),
  ('ALB-008', 'Formación de mocheta para ventana', 'ml', 15.00, 'Albañilería'),
  ('ALB-009', 'Falso techo continuo de placa de yeso laminado', 'm²', 26.00, 'Albañilería'),
  ('ALB-010', 'Falso techo registrable de escayola 60x60', 'm²', 22.00, 'Albañilería'),
  ('ALB-011', 'Recrecido y nivelación de suelo con mortero (espesor medio 3cm)', 'm²', 12.50, 'Albañilería'),
  ('ALB-012', 'Ayudas de albañilería a instalaciones', 'ud', 450.00, 'Albañilería'),
  ('ALB-013', 'Formación de bañera de obra con impermeabilización', 'ud', 380.00, 'Albañilería'),
  ('SOL-001', 'Solado de gres porcelánico rectificado 60x60', 'm²', 32.00, 'Solados y Alicatados'),
  ('SOL-002', 'Solado de gres porcelánico 45x45', 'm²', 28.00, 'Solados y Alicatados'),
  ('SOL-003', 'Alicatado de azulejo cerámico 30x60', 'm²', 26.00, 'Solados y Alicatados'),
  ('SOL-004', 'Alicatado de gres porcelánico rectificado', 'm²', 35.00, 'Solados y Alicatados'),
  ('SOL-005', 'Rodapié cerámico', 'ml', 8.50, 'Solados y Alicatados'),
  ('SOL-006', 'Suelo laminado AC4 con base aislante', 'm²', 24.00, 'Solados y Alicatados'),
  ('SOL-007', 'Suelo vinílico tipo click (SPC/LVT)', 'm²', 28.00, 'Solados y Alicatados'),
  ('SOL-008', 'Microcemento en suelos (sistema completo)', 'm²', 65.00, 'Solados y Alicatados'),
  ('SOL-009', 'Microcemento en paredes (sistema completo)', 'm²', 55.00, 'Solados y Alicatados'),
  ('SOL-010', 'Nivelación autonivelante para suelo (espesor 3mm)', 'm²', 10.00, 'Solados y Alicatados'),
  ('SOL-011', 'Mosaico hidráulico decorativo', 'm²', 48.00, 'Solados y Alicatados'),
  ('FON-001', 'Instalación completa de fontanería para baño (agua fría y caliente)', 'ud', 850.00, 'Fontanería'),
  ('FON-002', 'Instalación completa de fontanería para cocina', 'ud', 650.00, 'Fontanería'),
  ('FON-003', 'Instalación de inodoro completo (suministro y colocación)', 'ud', 320.00, 'Fontanería'),
  ('FON-004', 'Instalación de lavabo con pedestal o mueble', 'ud', 280.00, 'Fontanería'),
  ('FON-005', 'Instalación de plato de ducha con grifería', 'ud', 450.00, 'Fontanería'),
  ('FON-006', 'Instalación de bañera con grifería', 'ud', 520.00, 'Fontanería'),
  ('FON-007', 'Instalación de bidé completo', 'ud', 250.00, 'Fontanería'),
  ('FON-008', 'Instalación de fregadero de cocina con grifería', 'ud', 280.00, 'Fontanería'),
  ('FON-009', 'Tubería de cobre para agua (diámetro 15mm)', 'ml', 18.00, 'Fontanería'),
  ('FON-010', 'Tubería multicapa PEX para agua', 'ml', 12.00, 'Fontanería'),
  ('FON-011', 'Desagüe de PVC (diámetro 110mm)', 'ml', 14.00, 'Fontanería'),
  ('FON-012', 'Desagüe de PVC (diámetro 40mm)', 'ml', 8.50, 'Fontanería'),
  ('FON-013', 'Punto de desagüe de lavadora o lavavajillas', 'ud', 65.00, 'Fontanería'),
  ('FON-014', 'Instalación de calentador o termo eléctrico', 'ud', 180.00, 'Fontanería'),
  ('FON-015', 'Mampara de ducha fija o corredera', 'ud', 350.00, 'Fontanería'),
  ('FON-016', 'Inodoro suspendido con cisterna empotrada', 'ud', 580.00, 'Fontanería'),
  ('ELE-001', 'Punto de luz sencillo (cableado + mecanismo)', 'ud', 55.00, 'Electricidad'),
  ('ELE-002', 'Punto de luz conmutado', 'ud', 75.00, 'Electricidad'),
  ('ELE-003', 'Base de enchufe 16A (cableado + mecanismo)', 'ud', 48.00, 'Electricidad'),
  ('ELE-004', 'Toma de TV/datos (cableado + mecanismo)', 'ud', 52.00, 'Electricidad'),
  ('ELE-005', 'Cuadro eléctrico vivienda completo (hasta 10 circuitos)', 'ud', 380.00, 'Electricidad'),
  ('ELE-006', 'Circuito eléctrico nuevo (cableado completo)', 'ud', 180.00, 'Electricidad'),
  ('ELE-007', 'Instalación eléctrica completa vivienda (hasta 80m²)', 'ud', 2800.00, 'Electricidad'),
  ('ELE-008', 'Downlight LED empotrado', 'ud', 35.00, 'Electricidad'),
  ('ELE-009', 'Tira LED con perfil de aluminio', 'ml', 28.00, 'Electricidad'),
  ('ELE-010', 'Mecanismo eléctrico (interruptor/enchufe) gama media', 'ud', 12.00, 'Electricidad'),
  ('ELE-011', 'Cableado eléctrico en tubo corrugado empotrado', 'ml', 8.50, 'Electricidad'),
  ('ELE-012', 'Punto de conexión para aire acondicionado', 'ud', 120.00, 'Electricidad'),
  ('ELE-013', 'Extractor de baño con temporizador', 'ud', 85.00, 'Electricidad'),
  ('PIN-001', 'Pintura plástica lisa en paramentos verticales (2 manos)', 'm²', 8.50, 'Pintura'),
  ('PIN-002', 'Pintura plástica lisa en techos (2 manos)', 'm²', 9.50, 'Pintura'),
  ('PIN-003', 'Esmalte sintético sobre carpintería de madera', 'm²', 14.00, 'Pintura'),
  ('PIN-004', 'Esmalte sobre carpintería metálica', 'm²', 12.00, 'Pintura'),
  ('PIN-005', 'Imprimación selladora', 'm²', 3.50, 'Pintura'),
  ('PIN-006', 'Alisado y preparación de paramentos para pintura', 'm²', 6.00, 'Pintura'),
  ('PIN-007', 'Papel pintado con preparación de superficie', 'm²', 22.00, 'Pintura'),
  ('PIN-008', 'Pintura decorativa estuco o efecto', 'm²', 28.00, 'Pintura'),
  ('PIN-009', 'Lacado de puertas (ambas caras)', 'ud', 120.00, 'Pintura'),
  ('CAR-001', 'Puerta interior abatible lisa lacada en blanco', 'ud', 320.00, 'Carpintería'),
  ('CAR-002', 'Puerta interior corredera con guía oculta', 'ud', 480.00, 'Carpintería'),
  ('CAR-003', 'Puerta de entrada blindada', 'ud', 850.00, 'Carpintería'),
  ('CAR-004', 'Armario empotrado de 2 hojas correderas (frente completo)', 'ml', 380.00, 'Carpintería'),
  ('CAR-005', 'Armario empotrado de 2 hojas abatibles (frente completo)', 'ml', 350.00, 'Carpintería'),
  ('CAR-006', 'Ventana de aluminio con rotura de puente térmico y doble cristal', 'm²', 280.00, 'Carpintería'),
  ('CAR-007', 'Ventana de PVC con doble cristal', 'm²', 250.00, 'Carpintería'),
  ('CAR-008', 'Puerta balconera de aluminio con RPT', 'm²', 320.00, 'Carpintería'),
  ('CAR-009', 'Persiana de aluminio motorizada', 'm²', 180.00, 'Carpintería'),
  ('CAR-010', 'Moldura de escayola o poliuretano decorativa', 'ml', 12.00, 'Carpintería'),
  ('CAR-011', 'Premarco de madera para puerta interior', 'ud', 28.00, 'Carpintería'),
  ('IMP-001', 'Impermeabilización de plato de ducha con lámina', 'm²', 22.00, 'Impermeabilización'),
  ('IMP-002', 'Impermeabilización de cubierta plana con tela asfáltica', 'm²', 28.00, 'Impermeabilización'),
  ('IMP-003', 'Impermeabilización líquida en baños', 'm²', 15.00, 'Impermeabilización'),
  ('IMP-004', 'Impermeabilización de terraza transitable', 'm²', 35.00, 'Impermeabilización'),
  ('IMP-005', 'Banda impermeable para juntas y esquinas', 'ml', 6.50, 'Impermeabilización'),
  ('CER-001', 'Barandilla de acero inoxidable con vidrio', 'ml', 180.00, 'Cerrajería'),
  ('CER-002', 'Barandilla de hierro forjado', 'ml', 120.00, 'Cerrajería'),
  ('CER-003', 'Reja de seguridad para ventana', 'm²', 95.00, 'Cerrajería'),
  ('CER-004', 'Estructura metálica para altillo o entreplanta', 'm²', 180.00, 'Cerrajería'),
  ('CER-005', 'Escalera metálica de tramo recto', 'ud', 2200.00, 'Cerrajería'),
  ('INS-001', 'Instalación de aire acondicionado split (hasta 3.5kW)', 'ud', 950.00, 'Instalaciones'),
  ('INS-002', 'Instalación de aire acondicionado split (hasta 5kW)', 'ud', 1200.00, 'Instalaciones'),
  ('INS-003', 'Instalación de caldera de gas condensación', 'ud', 2200.00, 'Instalaciones'),
  ('INS-004', 'Radiador de aluminio (por elemento)', 'ud', 28.00, 'Instalaciones'),
  ('INS-005', 'Suelo radiante (instalación completa)', 'm²', 55.00, 'Instalaciones'),
  ('INS-006', 'Tubería de cobre para gas', 'ml', 22.00, 'Instalaciones'),
  ('INS-007', 'Conducto de ventilación en aluminio flexible', 'ml', 15.00, 'Instalaciones'),
  ('INS-008', 'Aerotermia (bomba de calor aire-agua)', 'ud', 4500.00, 'Instalaciones'),
  ('INS-009', 'Toallero eléctrico de baño', 'ud', 120.00, 'Instalaciones'),
  ('COC-001', 'Mueble bajo de cocina (módulo 60cm)', 'ud', 180.00, 'Cocina'),
  ('COC-002', 'Mueble alto de cocina (módulo 60cm)', 'ud', 150.00, 'Cocina'),
  ('COC-003', 'Mueble columna de cocina', 'ud', 320.00, 'Cocina'),
  ('COC-004', 'Encimera de cuarzo compacto', 'ml', 180.00, 'Cocina'),
  ('COC-005', 'Encimera de granito natural', 'ml', 150.00, 'Cocina'),
  ('COC-006', 'Encimera de laminado HPL', 'ml', 85.00, 'Cocina'),
  ('COC-007', 'Instalación de placa de inducción', 'ud', 120.00, 'Cocina'),
  ('COC-008', 'Instalación de horno empotrado', 'ud', 80.00, 'Cocina'),
  ('COC-009', 'Instalación de campana extractora', 'ud', 150.00, 'Cocina'),
  ('COC-010', 'Instalación de lavavajillas empotrado', 'ud', 85.00, 'Cocina'),
  ('LIM-001', 'Limpieza final de obra en vivienda', 'm²', 4.50, 'Limpieza'),
  ('LIM-002', 'Limpieza de cristales post-obra', 'm²', 3.00, 'Limpieza'),
  ('LIM-003', 'Gestión de residuos y escombros', 'm³', 32.00, 'Limpieza'),
  ('VAR-001', 'Protección de zonas no afectadas por la obra', 'm²', 3.50, 'Varios'),
  ('VAR-002', 'Montaje y desmontaje de andamio interior', 'ud', 250.00, 'Varios'),
  ('VAR-003', 'Licencia y tasas municipales de obra menor', 'ud', 350.00, 'Varios'),
  ('VAR-004', 'Proyecto técnico para obra menor', 'ud', 600.00, 'Varios'),
  ('VAR-005', 'Estudio de seguridad y salud', 'ud', 400.00, 'Varios');
-- Total: 124 rows
